import mongoose from "mongoose";
import dotenv from "dotenv";
import Laptop from "./models/Laptop.js";

dotenv.config();

export const laptopsData = [
  {
    laptopId: "lap-001",
    name: "AeroBook 14",
    brand: "Aerion",
    series: "Ultralight",
    price: 64990,
    rating: 4.3,
    processor: { brand: "Intel", model: "Core i5-1240P", cores: 12, threads: 16, baseClock: "1.7 GHz", boostClock: "4.4 GHz" },
    ram: { sizeGB: 16, type: "LPDDR5", speedMHz: 5200 },
    storage: [{ type: "NVMe", sizeGB: 512 }],
    graphics: { type: "integrated", model: "Iris Xe" },
    display: { sizeInches: 14, resolution: "1920x1200", refreshHz: 60, panel: "IPS", aspect: "16:10" },
    battery: { capacityWh: 56, claimedHours: "Up to 10 hrs", fastCharge: true },
    weightKg: 1.28,
    os: "Windows 11 Home",
    ports: ["USB-C (PD)", "USB-A", "HDMI 2.0", "3.5mm"],
    connectivity: { wifi: "Wi-Fi 6", bluetooth: "5.2" },
    warrantyYears: 1,
  },
  {
    laptopId: "lap-002",
    name: "Creator 15 OLED",
    brand: "Nextron",
    series: "Creator",
    price: 119990,
    rating: 4.6,
    processor: { brand: "AMD", model: "Ryzen 7 7840HS", cores: 8, threads: 16, baseClock: "3.8 GHz", boostClock: "5.1 GHz" },
    ram: { sizeGB: 32, type: "DDR5", speedMHz: 5600, upgradableToGB: 64 },
    storage: [{ type: "NVMe", sizeGB: 1000 }],
    graphics: { type: "dedicated", model: "GeForce RTX 4060", vramGB: 8 },
    display: { sizeInches: 15.6, resolution: "2880x1800", refreshHz: 120, panel: "OLED", aspect: "16:10" },
    battery: { capacityWh: 71, claimedHours: "Up to 8 hrs", fastCharge: true },
    weightKg: 1.79,
    os: "Windows 11 Pro",
    ports: ["Thunderbolt 4", "USB-A", "HDMI 2.1", "SD UHS-II", "3.5mm"],
    connectivity: { wifi: "Wi-Fi 6E", bluetooth: "5.3" },
    warrantyYears: 2,
  },
  {
    laptopId: "lap-003",
    name: "StudyMate 13",
    brand: "EduTech",
    series: "Student",
    price: 42990,
    rating: 4.1,
    processor: { brand: "Intel", model: "Core i3-1215U", cores: 6, threads: 8, baseClock: "1.2 GHz", boostClock: "4.4 GHz" },
    ram: { sizeGB: 8, type: "DDR4", speedMHz: 3200, upgradableToGB: 32 },
    storage: [{ type: "NVMe", sizeGB: 256 }],
    graphics: { type: "integrated", model: "UHD Graphics" },
    display: { sizeInches: 13.3, resolution: "1920x1080", refreshHz: 60, panel: "IPS", aspect: "16:9" },
    battery: { capacityWh: 45, claimedHours: "Up to 12 hrs" },
    weightKg: 1.2,
    os: "Windows 11 Home",
    ports: ["USB-C", "USB-A", "HDMI 1.4", "3.5mm"],
    connectivity: { wifi: "Wi-Fi 6", bluetooth: "5.1" },
    warrantyYears: 1,
  },
  {
    laptopId: "lap-004",
    name: "GameForge 16",
    brand: "Forge",
    series: "Gaming",
    price: 149990,
    rating: 4.7,
    processor: { brand: "Intel", model: "Core i7-13700H", cores: 14, threads: 20, baseClock: "2.4 GHz", boostClock: "5.0 GHz" },
    ram: { sizeGB: 32, type: "DDR5", speedMHz: 5200, upgradableToGB: 64 },
    storage: [{ type: "NVMe", sizeGB: 1000 }, { type: "NVMe", sizeGB: 1000 }],
    graphics: { type: "dedicated", model: "GeForce RTX 4070", vramGB: 8 },
    display: { sizeInches: 16, resolution: "2560x1600", refreshHz: 165, panel: "IPS", aspect: "16:10" },
    battery: { capacityWh: 80, claimedHours: "Up to 6 hrs", fastCharge: true },
    weightKg: 2.25,
    os: "Windows 11 Home",
    ports: ["Thunderbolt 4", "USB-A", "HDMI 2.1", "RJ45", "3.5mm"],
    connectivity: { wifi: "Wi-Fi 6E", bluetooth: "5.3" },
    warrantyYears: 2,
  },
  {
    laptopId: "lap-005",
    name: "HP Pavilion Aero",
    brand: "HP",
    series: "Pavilion",
    price: 67990,
    rating: 4.5,
    processor: { brand: "AMD", model: "Ryzen 7 5800U", cores: 8, threads: 16, baseClock: "1.9 GHz", boostClock: "4.4 GHz" },
    ram: { sizeGB: 16, type: "DDR4", speedMHz: 3200 },
    storage: [{ type: "NVMe", sizeGB: 512 }],
    graphics: { type: "integrated", model: "Radeon Graphics" },
    display: { sizeInches: 13.3, resolution: "1920x1200", refreshHz: 60, panel: "IPS", aspect: "16:10" },
    battery: { capacityWh: 45, claimedHours: "Up to 10 hrs", fastCharge: true },
    weightKg: 0.97,
    os: "Windows 11 Home",
    ports: ["USB-C", "USB-A", "HDMI", "3.5mm"],
    connectivity: { wifi: "Wi-Fi 6", bluetooth: "5.2" },
    warrantyYears: 1,
  },
  {
    laptopId: "lap-006",
    name: "Lenovo IdeaPad Gaming 3",
    brand: "Lenovo",
    series: "IdeaPad",
    price: 72990,
    rating: 4.2,
    processor: { brand: "Intel", model: "Core i5-12450H", cores: 8, threads: 12, baseClock: "2.0 GHz", boostClock: "4.4 GHz" },
    ram: { sizeGB: 16, type: "DDR5", speedMHz: 4800 },
    storage: [{ type: "NVMe", sizeGB: 512 }],
    graphics: { type: "dedicated", model: "RTX 3050" },
    display: { sizeInches: 15.6, resolution: "1920x1080", refreshHz: 120, panel: "IPS", aspect: "16:9" },
    battery: { capacityWh: 60, claimedHours: "Up to 6 hrs", fastCharge: true },
    weightKg: 2.3,
    os: "Windows 11 Home",
    ports: ["USB-C", "USB-A", "HDMI", "Ethernet", "3.5mm"],
    connectivity: { wifi: "Wi-Fi 6", bluetooth: "5.1" },
    warrantyYears: 1,
  },
  {
    laptopId: "lap-007",
    name: "Apple MacBook Air M2",
    brand: "Apple",
    series: "MacBook Air",
    price: 114900,
    rating: 4.8,
    processor: { brand: "Apple", model: "M2", cores: 8, threads: 8, baseClock: "3.5 GHz", boostClock: "N/A" },
    ram: { sizeGB: 8, type: "Unified", speedMHz: 6400 },
    storage: [{ type: "NVMe", sizeGB: 256 }],
    graphics: { type: "integrated", model: "M2 GPU (8-core)" },
    display: { sizeInches: 13.6, resolution: "2560x1664", refreshHz: 60, panel: "Liquid Retina", aspect: "16:10" },
    battery: { capacityWh: 52, claimedHours: "Up to 15 hrs", fastCharge: true },
    weightKg: 1.24,
    os: "macOS Ventura",
    ports: ["MagSafe 3", "USB-C Thunderbolt 4", "3.5mm"],
    connectivity: { wifi: "Wi-Fi 6", bluetooth: "5.0" },
    warrantyYears: 1,
  },
  {
    laptopId: "lap-008",
    name: "Dell Inspiron 15",
    brand: "Dell",
    series: "Inspiron",
    price: 58990,
    rating: 4.1,
    processor: { brand: "Intel", model: "Core i5-1135G7", cores: 4, threads: 8, baseClock: "2.4 GHz", boostClock: "4.2 GHz" },
    ram: { sizeGB: 8, type: "DDR4", speedMHz: 3200 },
    storage: [{ type: "NVMe", sizeGB: 512 }],
    graphics: { type: "integrated", model: "Iris Xe" },
    display: { sizeInches: 15.6, resolution: "1920x1080", refreshHz: 60, panel: "WVA", aspect: "16:9" },
    battery: { capacityWh: 54, claimedHours: "Up to 8 hrs", fastCharge: true },
    weightKg: 1.85,
    os: "Windows 11 Home",
    ports: ["USB-C", "USB-A", "HDMI", "3.5mm"],
    connectivity: { wifi: "Wi-Fi 6", bluetooth: "5.0" },
    warrantyYears: 1,
  },
  {
    laptopId: "lap-009",
    name: "ASUS TUF Gaming F15",
    brand: "ASUS",
    series: "TUF",
    price: 84990,
    rating: 4.6,
    processor: { brand: "Intel", model: "Core i7-12700H", cores: 14, threads: 20, baseClock: "2.3 GHz", boostClock: "4.7 GHz" },
    ram: { sizeGB: 16, type: "DDR5", speedMHz: 4800 },
    storage: [{ type: "NVMe", sizeGB: 1024 }],
    graphics: { type: "dedicated", model: "RTX 3060" },
    display: { sizeInches: 15.6, resolution: "1920x1080", refreshHz: 144, panel: "IPS", aspect: "16:9" },
    battery: { capacityWh: 90, claimedHours: "Up to 7 hrs", fastCharge: true },
    weightKg: 2.3,
    os: "Windows 11 Home",
    ports: ["USB-C", "USB-A", "HDMI", "Ethernet", "3.5mm"],
    connectivity: { wifi: "Wi-Fi 6", bluetooth: "5.2" },
    warrantyYears: 1,
  },
  {
    laptopId: "lap-0010",
    name: "MSI Katana GF66",
    brand: "MSI",
    series: "Katana",
    price: 92990,
    rating: 4.4,
    processor: { brand: "Intel", model: "Core i7-11800H", cores: 8, threads: 16, baseClock: "2.3 GHz", boostClock: "4.6 GHz" },
    ram: { sizeGB: 16, type: "DDR4", speedMHz: 3200 },
    storage: [{ type: "NVMe", sizeGB: 512 }],
    graphics: { type: "dedicated", model: "RTX 3050 Ti" },
    display: { sizeInches: 15.6, resolution: "1920x1080", refreshHz: 144, panel: "IPS", aspect: "16:9" },
    battery: { capacityWh: 53, claimedHours: "Up to 5 hrs", fastCharge: false },
    weightKg: 2.25,
    os: "Windows 11 Home",
    ports: ["USB-C", "USB-A", "HDMI", "Ethernet"],
    connectivity: { wifi: "Wi-Fi 6", bluetooth: "5.2" },
    warrantyYears: 2,
  },
  {
    laptopId: "lap-0011",
    name: "Samsung Galaxy Book2 Pro",
    brand: "Samsung",
    series: "Galaxy Book",
    price: 94990,
    rating: 4.7,
    processor: { brand: "Intel", model: "Core i7-1260P", cores: 12, threads: 16, baseClock: "2.1 GHz", boostClock: "4.7 GHz" },
    ram: { sizeGB: 16, type: "LPDDR5", speedMHz: 5200 },
    storage: [{ type: "NVMe", sizeGB: 512 }],
    graphics: { type: "integrated", model: "Iris Xe" },
    display: { sizeInches: 15.6, resolution: "1920x1080", refreshHz: 60, panel: "AMOLED", aspect: "16:9" },
    battery: { capacityWh: 63, claimedHours: "Up to 15 hrs", fastCharge: true },
    weightKg: 1.1,
    os: "Windows 11 Home",
    ports: ["USB-C", "USB-A", "HDMI", "3.5mm"],
    connectivity: { wifi: "Wi-Fi 6E", bluetooth: "5.1" },
    warrantyYears: 1,
  },
];

// Run as script
const runSeed = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");
    await Laptop.deleteMany({});
    await Laptop.insertMany(laptopsData);
    console.log(`✅ Seeded ${laptopsData.length} laptops`);
    process.exit(0);
  } catch (err) {
    console.error("Seed error:", err);
    process.exit(1);
  }
};

// Only run when executed directly (not imported)
if (process.argv[1]?.includes("seed")) {
  runSeed();
}
